=== lopezdsr/GDM-split-msgs-tutorial/src/SharedLib_Split1msgintoNmsgs/CustomerOrdersPerStore.xsd
<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://gdm/schema/models" xmlns:gdmNamespace="http://gdm/schema/models" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="CustomerOrdersPerStore">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element default="123" name="StoreCode" type="xsd:int"/>
				<xsd:element default="123" name="Operator" type="xsd:int"/>
				<xsd:element default="2011-01-01" name="Date" type="xsd:date"/>
				<xsd:element default="10:10:10" name="Time" type="xsd:time"/>
				<xsd:element default="John" name="Customer" type="xsd:string"/>
				<xsd:element default="123" name="NumItems" type="xsd:int"/>
				<xsd:element maxOccurs="unbounded" name="Item">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element default="123" name="ItemCode" type="xsd:int"/>
							<xsd:element default="0.20" name="Price" type="xsd:decimal"/>
							<xsd:element default="5" name="Quantity" type="xsd:positiveInteger"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="unbounded" name="ItemDescription">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element default="123" name="ItemCode" type="xsd:int"/>
							<xsd:element default="A" name="Description" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element default="0.20" name="Total" type="xsd:decimal"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== lopezdsr/GDM-split-msgs-tutorial/src/GDM_Transform_Split1msgintoNmsgs/MultipleCustomerOrdersPerStore.xml
<?xml version="1.0" encoding="UTF-8"?>
<gdmNamespace:CustomerOrdersPerStore xmlns:gdmNamespace="http://gdm/schema/models" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gdm/schema/models CustomerOrdersPerStore.xsd ">
  <StoreCode>5</StoreCode>
  <Operator>Op123</Operator>
  <Date>2011-01-01</Date>
  <Time>10:10:10</Time>
  <Customer>John</Customer>
 <NumItems>2</NumItems>
  <Item>
    <ItemCode>1</ItemCode>
    <Price>0.20</Price>
    <Quantity>5</Quantity>
  </Item>
  <Item>
    <ItemCode>2</ItemCode>
    <Price>0.60</Price>
    <Quantity>2</Quantity>
  </Item>
  <ItemDescription>
    <ItemCode>1</ItemCode>
    <Description>Car</Description>
  </ItemDescription> <ItemDescription>
    <ItemCode>2</ItemCode>
    <Description>Bike</Description>
  </ItemDescription>
  <Total>0.20</Total>
</gdmNamespace:CustomerOrdersPerStore>
